Included support for gnome GUI and other minor modifications

diff --git a/create-vm b/create-vm
--- a/create-vm
+++ b/create-vm
@@ -2,16 +2,50 @@
 
 START_TIME=$SECONDS
 
-DIST=zesty          \
-ARCH=64             \
-GUI=yes             \
-VNX=yes             \
-HNAME=vnx-vm        \
-NEWUSER=vnx         \
-NEWPASSWD=xxxx      \
-VMLANG=es           \
-MEM=2048            \
-VCPUS=4             \
+# Set default values
+#export DIST=xenial
+export DIST=bionic
+export ARCH=64
+export GUI=no
+export VNX=no
+export HNAME=vnx-vm
+export NEWUSER=vnx
+export NEWPASSWD=xxxx
+export VMLANG=es
+export MEM=2048
+export VCPUS=2
+
+Usage="--
+-- Usage: create-vm [-c <conf_file>] [-h]
+--"
+
+while getopts ":hc:" opt; do
+  case $opt in
+    c)
+      CFGFILE=$OPTARG
+      if [ ! -e $CFGFILE ]; then 
+        echo "-- ERROR: config file '$CFGFILE' not found"
+        exit 1
+      fi
+      source $CFGFILE
+      ;;
+    h)
+      #echo "-h was triggered!" >&2
+      echo "$Usage"
+      exit 0
+      ;;
+    \?)
+      echo "-- ERROR: invalid option -$OPTARG" >&2
+      ;;
+    :)
+      echo "-- ERROR: option -$OPTARG requires an argument" >&2
+      echo "$Usage"
+      exit 1
+      ;;
+  esac
+done
+
+echo "DIST=$DIST"
 vagrant up
 
 ELAPSED_TIME=$(($SECONDS - $START_TIME))
